# -*- coding: utf-8 -*-
"""Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YL3cU1ndrIwhF2Q9XtAsAPDAYj1CkdNB
"""

import json
import numpy as np
import gradio as gr
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image

# Load model
model = load_model("eye_efficient_b3_model.h5")

# Load class names
with open("CLASS_NAMES.json", "rb") as f:
    CLASS_NAMES = json.load(f)


def prepare_image(img, target_size=(300, 300)):
    img = img.resize(target_size)
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)  # Important for EfficientNet
    return img_array


def predict_image(img):
    x = prepare_image(img, target_size=(300, 300))
    preds = model.predict(x)
    class_idx = np.argmax(preds, axis=1)[0]
    class_name = CLASS_NAMES[class_idx]
    confidence = preds[0][class_idx]
    return f"{class_name} ({confidence*100:.2f}%)"




iface = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="Eye Disease Classifier",
    description="Upload a retinal image and predict eye disease class"
)

iface.launch()

